services:
  - type: web
    name: backend-ql-vunglu
    runtime: node
    region: singapore
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: APP_PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://ql-vunglu.site
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: postgres
      - key: DB_SYNC
        value: true
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
