import { Routes } from '@nestjs/core';
import { AuthsModule } from 'src/modules/auths/auths.module';
import { ChatsModule } from 'src/modules/chats/chats.module';
import { HumanResourcesModule } from 'src/modules/human-resources/human-resources.module';
import { NotificationsModule } from 'src/modules/notifications/notifications.module';
import { ReflectionsModule } from 'src/modules/reflections/reflections.module';
import { ResidentsModule } from 'src/modules/residents/residents.module';
import { RolesModule } from 'src/modules/roles/roles.module';
import { UsersModule } from 'src/modules/users/users.module';
import { VerificationsModule } from 'src/modules/verifications/verifications.module';

export const routes: Routes = [
  { path: 'auth', module: AuthsModule },         // /api/auth/...
  { path: 'users', module: UsersModule },         // /api/users/...
  { path: 'roles', module: RolesModule },         // /api/roles/...
  { path: 'human-resources', module: HumanResourcesModule }, // /api/human-resources/...
  { path: 'residents', module: ResidentsModule }, // /api/residents/...
  { path: 'reports', module: ReflectionsModule }, // /api/reports/... (reflections module)
  { path: 'verifications', module: VerificationsModule }, // /api/verifications/...
  { path: 'chats', module: ChatsModule },         // /api/chats/...
  { path: 'notifications', module: NotificationsModule }, // /api/notifications/...
];
